// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDenrszze5ggoYcNMWK0DXPsK_VQ9ymN8',
    appId: '1:899082501797:android:2d958961d299e4cb1d974c',
    messagingSenderId: '899082501797',
    projectId: 'metabolic-waqas',
    storageBucket: 'metabolic-waqas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuztjGIxM3YxLZyBkvZlGuBTKn8E0wWYs',
    appId: '1:899082501797:ios:553e8f8639b80e741d974c',
    messagingSenderId: '899082501797',
    projectId: 'metabolic-waqas',
    storageBucket: 'metabolic-waqas.firebasestorage.app',
    iosBundleId: 'com.waqas.workoutJournal',
  );
}
